In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("berkanoztas/synthetic-transaction-monitoring-dataset-aml")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.1).
Downloading from https://www.kaggle.com/api/v1/datasets/download/berkanoztas/synthetic-transaction-monitoring-dataset-aml?dataset_version_number=2...

100%|██████████| 193M/193M [00:05<00:00, 38.5MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/berkanoztas/synthetic-transaction-monitoring-dataset-aml/versions/2

In [4]:
path+'/SAML-D.csv'

'/root/.cache/kagglehub/datasets/berkanoztas/synthetic-transaction-monitoring-dataset-aml/versions/2/SAML-D.csv'

In [5]:
import pandas as pd
data=pd.read_csv(path+'/SAML-D.csv')

In [6]:
data[:2]

,Time,Date,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering,Laundering_type
0,10:35:19,2022-10-07,8724731955,2769355426,1459.15,UK pounds,UK pounds,UK,UK,Cash Deposit,0,Normal_Cash_Deposits
1,10:35:20,2022-10-07,1491989064,8401255335,6019.64,UK pounds,Dirham,UK,UAE,Cross-border,0,Normal_Fan_Out

In [11]:
df=data.drop(['Time','Date','Laundering_type'],axis=1)

In [12]:
df[:2]

,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering
0,8724731955,2769355426,1459.15,UK pounds,UK pounds,UK,UK,Cash Deposit,0
1,1491989064,8401255335,6019.64,UK pounds,Dirham,UK,UAE,Cross-border,0

In [13]:
from collections import Counter
Counter(df['Is_laundering'])

Counter({0: 9494979, 1: 9873})

In [16]:
from sklearn.preprocessing import LabelEncoder
df1=df.apply(LabelEncoder().fit_transform)

In [17]:
df1[:2]

,Sender_account,Receiver_account,Amount,Payment_currency,Received_currency,Sender_bank_location,Receiver_bank_location,Payment_type,Is_laundering
0,255277,180462,144979,10,10,16,16,1,0
1,43554,548141,597254,10,1,16,15,5,0

In [18]:
target=df1['Is_laundering']
features=df1.drop(['Is_laundering'],axis=1)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,target,test_size=0.2)

In [22]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [23]:
lr.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
pred=lr.predict(X_test)

In [29]:
Counter(pred)

Counter({np.int64(0): 1900971})

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.9989589530823985

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1898992
           1       0.00      0.00      0.00      1979

    accuracy                           1.00   1900971
   macro avg       0.50      0.50      0.50   1900971
weighted avg       1.00      1.00      1.00   1900971

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))